#ifndef _TI84RC_SETTINGS_H
#define _TI84RC_SETTINGS_H

#define BACKBUFFER_WIDTH  96
#define BACKBUFFER_HEIGHT 64

#define PIXEL_SCALE 8

#define WINDOW_WIDTH (PIXEL_SCALE * BACKBUFFER_WIDTH)
#define WINDOW_HEIGHT (PIXEL_SCALE * BACKBUFFER_HEIGHT)

#endif
